### PR TITLE
docs(trace): bugfixes to the release 3.2 version of the Traceability KIT

### PR DESCRIPTION
**Pull request by markuskeidl**
Fix several bugs in the Traceability KIT for release 3.2:
- KITs are using a dark mode, so images should also fit to that mode.
- Fixed deprecated references to release 3.0/3.1 in the software development view

### CODE REVIEW

**Comment by markuskeidl** [comment]
This pull request is not merged into 3.1 - it's also relevant for 3.2 - Should I just update it for 3.2 and we forget about 3.1? @mhellmeier

**Comment by mhellmeier** [comment]
> This pull request is not merged into 3.1 - it's also relevant for 3.2 - Should I just update it for 3.2 and we forget about 3.1? @mhellmeier

Thanks, @markuskeidl! Yes, I think this would be the easiest way. Otherwise, we maybe have to go through the whole acceptance process again. Would be great if you could change the target branch to the 3.2 one and adjust the pull request accordingly.

**Comment by markuskeidl** [comment]
Pull request is now adjusted accordingly.

**Review by mhellmeier — APPROVED** [review]
LGTM

**Pull request merged**
