### PR TITLE
docs(trace): updated KIT with changes because of AAS v3.0

### PR DESCRIPTION
**Pull request by markuskeidl**
With Catena-X release 3.2, the DTR switches to the AAS v3.0 version of the AAS standard. This requires updates to parts of the KIT that reference DTR topics.

### CODE REVIEW

**Review by mhellmeier — CHANGES_REQUESTED** [review]
The current PR wants to merge the changes from `docs/trace-update-to-aas30` into `main`. For release 3.2, we want to collect all Traceability KIT changes in `docs/trace-release-3.2`. So please change the target branch from `main` to `docs/trace-release-3.2`.
https://github.com/catenax-ng/eclipse-tractusx.github.io/tree/docs/trace-release-3.2

**Comment by markuskeidl** [comment]
Target branch changed to docs/trace-release-3.2

**Review by mhellmeier — CHANGES_REQUESTED** [review]
The merge conflicts should be solved before merging.

**Comment by markuskeidl** [comment]
Somehow I messed up this pull request by merging changes from the main repo into this brachen. Not sure if that can be fixed. Maybe create a new pull request?

**Comment by mhellmeier** [comment]
There are two possibilities:
1. Force-pushing to this branch to fix the issues
2. Start from scratch with a totally new branch and pull request

**Pull request closed without merging**
