### PR TITLE
docs(ic): added concept for reducing number of digital twins for instantiated parts

### PR DESCRIPTION
**Pull request by markuskeidl**
This is a first draft for the concept discussed in Traceability.

### CODE REVIEW

**Review by matgnt — APPROVED** [review]

**Comment by arnoweiss** [comment]
This would require substantial consequences on other standards like CX-0002. I don't think that adding the concept to the kit now is premature.

**Comment by markuskeidl** [comment]
I don't see these consequences. Do you have any examples of what would have to be changed in these other standards?

Also, I think you mean "I think that adding ..." - as written like now, you agree with the PR, right?

**Comment by arnoweiss** [comment]
Currently, Data Providers are free to implement the the `POST /invoke` operations but not required. I'm unsure if it would suffice to make it mandatory in CX-0126 OR if CX-0002 would have to change. Either way, I'm pretty sure this would incompatibly change the entire logic of the Industry Core (the separation into `PartInstance` and `PartType` twins, the asset-centricity, the specificAssetIds as platform for other use-cases)

**Review by arnoweiss — CHANGES_REQUESTED** [review]
This is effectively saying "Deprecate CX-0126". Its based on the assumption that maintaining twins for each `PartInstance` will be too expensive or slow - which sounds plausible but I haven't seen proven. 

And even if that assumption was true, we should investigate other options to lower operational cost like limited retention periods for DTs.

**Comment by markuskeidl** [comment]
I still don't understand your concerns. 
- This draft describes a concept, currently, so it is not yet finished which means it needs more discussion and work. 
- It also does not force data providers to do anything. If a data provide wants to create digital twins for everything, they are totally free to do so. That's even the default strategy. No data provider is forced to implement /invoke with the above concept.
- Of course, if a data provider decides to use the above solution (and the data provider is the one deciding this, no one else), then data consumers need to be able to use this solution. So, as I see it, it's more of a challenge for data consumers which need to support this if they want to consume data from a provider using the above solution. 

You are right that currently, it's just risk that efficiency might be an issue, but it's not something that already happend. It could also be that we will have no issues at all and never need to use this solution. I would be fine with that as well. 

Other options could also be valid, but right now, no one does that or even cares about that, I think.

**Review by mhellmeier — APPROVED** [review]
Can be merged since it is only an information and not a mandatory new concept.

**Pull request merged**
