### PR TITLE
Update quality notification API to implement standard header

### PR DESCRIPTION
**Pull request by DrDanielMetz**
Changed the request payloads to create and update a quality investigation/alert. Now, the standard message header is used. As a consequence, the traceability specific content is also adapted accordingly.

The endpoint to resolve a quality alert/investigation has been removed.
This one has never been implemented and is considered as not usable/useful.

### CODE REVIEW

**Comment by DrDanielMetz** [comment]
> One question, not sure: if you change the version from 1.1 to 1.2 and remove 1.1 isn't that a breaking change. Meaning: to be backwards compatible, shouldn't we add 1.2, but still keep 1.1 as default until release 24.05? @DrDanielMetz

@markuskeidl: Yes, you are right. I will change it like this.

**Comment by markuskeidl** [comment]
I would explain that in the Software Development View as it's information that is meant for developers. As you can see in the most recent https://github.com/catenax-ng/eclipse-tractusx.github.io/pull/40 the current assumption is that we need an EDC asset for every minor version (1.1 and 1.2), but not for patch versions. 

The consumer can use the property cx-common:version to determine which API version the asset represents.

**Review by mhellmeier — CHANGES_REQUESTED** [review]
The new openAPI file needs to be configured in the Docusaurus configuration to be recognized in the build process.

I can help you on this if you'd like.

**Review by mhellmeier — APPROVED** [review]
Adjusted and regenerated everything as described.

**Pull request merged**
